#!/usr/bin/env python3
import os
import subprocess
import sys

EXPECTED_VERSION="verusfmt 0.1.6"
ACTUAL_VERSION=subprocess.check_output(["verusfmt", "--version"]).strip().decode("utf-8")

if EXPECTED_VERSION != ACTUAL_VERSION:
    sys.stderr.write(f"Expected {EXPECTED_VERSION}, found {ACTUAL_VERSION}. Update verusfmt with:\n")
    sys.stderr.write(f"cargo install verusfmt\n")
    sys.exit(1)

cwd = os.getcwd()
find_cmd = ["find", cwd, "-name", "*.rs"]
p1 = subprocess.Popen(find_cmd, stdout=subprocess.PIPE)
xargs_cmd = ["xargs", "verusfmt"]
p2 = subprocess.Popen(xargs_cmd + ["--check"], stdin=p1.stdout, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
rc = p2.wait()
if rc == 0:
    sys.exit(0)
sys.stderr.write(f"verusfmt failed. Format all source with:\n")
cmd = (" ".join(find_cmd)) + " | " + (" ".join(xargs_cmd))
sys.stderr.write(cmd+"\n")
