#!/usr/bin/env python3
"""Builds the docs/veridoc.md documentation file."""

from lib_deps import *

def readVeriDoc(path):
    lines = open(path).readlines()
    offset = 0
    veridoc = []
    while lines[offset].startswith("include"):
        offset += 1
    while lines[offset].startswith("//"):
        veridoc.append(lines[offset][2:].strip())
        offset += 1
    return "\n".join(veridoc)

def toposortFiles(candidates):
    return toposortGroup([IncludeReference(None, 0, line) for line in candidates])

def separate(irefs, l):
    match = set([i for i in irefs if l(i.normPath)])
    remainder = irefs - match
    return (match, remainder)

class Documentater:
    def __init__(self):
        TOP=IncludeReference(None, 0, "Impl/Bundle.i.dfy")
        allIrefs = set(depsFromDfySource(TOP))
        (allLibs, allBetree) = separate(allIrefs, lambda p: p.startswith("lib/"))
        (sLibs, iLibs) = separate(allLibs, lambda p: p.endswith(".s.dfy"))
        (sBetree, iBetree) = separate(allBetree, lambda p: p.endswith(".s.dfy"))

        self.veridoc_fp = open("docs/veridoc.md", "w")
        self.present(sLibs, "Trusted Libraries")
        self.present(iLibs, "Verified Libraries")
        self.present(sBetree, "Trusted Map Spec")
        self.present(iBetree, "Verified B-epsilon Tree")
    
    def present(self, irefs, headerText):
        files = [i.normPath for i in irefs]
        self.veridoc_fp.write("# %s\n\n" % headerText)
        for iref in toposortFiles(files):
            self.veridoc_fp.write("**%s** " % iref.normPath)
            self.veridoc_fp.write(readVeriDoc(iref.normPath))
            self.veridoc_fp.write("\n")
            self.veridoc_fp.write("\n")

Documentater()
